spring.application.name=MoyKlassMCPServer
spring.ai.mcp.server.name=moyklass-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=sync
spring.ai.mcp.server.base-url=/api/v1
spring.ai.mcp.server.sse-message-endpoint=/mcp/message
spring.ai.mcp.server.capabilities.completion=true
spring.ai.mcp.server.capabilities.prompt=true
spring.ai.mcp.server.capabilities.resource=true
spring.ai.mcp.server.capabilities.tool=true

# Change notifications
spring.ai.mcp.server.resource-change-notification=true
spring.ai.mcp.server.tool-change-notification=true
spring.ai.mcp.server.prompt-change-notification=true

crm.api.url=https://api.moyklass.com
crm.api.key=123
